---
title: "Forecast Averaging: Inflation Models in R"
subtitle: "Use ensemble forecasting to predict 1-year ahead inflation using data from FRED"
author: "Sean Cannon"
date: "`r format(Sys.Date(),'%B %d, %Y')`"
output: 
  html_document:
    df_print: paged
    code_folding: "hide"
    toc: no
    fig_caption: yes
    theme: simplex
    toc_float: no
---
```{r setup, include=FALSE}
rm(list=ls())
graphics.off()
knitr::opts_chunk$set(echo = TRUE,
                      message = TRUE,
                      warning = TRUE)
```

```{r packages, message=FALSE, warning=FALSE}
require(fpp3)
require(tsibble)
require(tidyverse)
require(tidyquant)
require(kableExtra)
require(reshape2)
```

<br>
<h5>Background</h5>
<br>

Introduce the topics and objectives of the project here

<br>
<h5>Data and Variables</h5>
<br>
```{r load_data}
# Vector of variables to be gathered:
Variables <- c("PCEPI","UNRATE","EXPINF1YR","MICH","INDPRO")

# Use tidyquant function tq_get to gather economic data from FRED and format as a tsibble
fred_data <- tq_get(Variables,
                    get = "economic.data",
                    from = "1982-01-01") %>%
  mutate(Month = yearmonth(date), value = price) %>%
  select(-c(date, price)) %>%
  as_tsibble(index = Month, key = symbol)

# Pivot the data to be in a more conventional wide format
fred_dataw <- fred_data %>%
  pivot_wider(names_from = symbol, values_from = value) %>%
  as_tsibble()
```

```{r data_table}
# Define description and units vectors for the table
Description <- c("Personal Consumption Expenditures: Chain-type Price Index","Unemployment Rate","1-Year Expected Inflation","University of Michigan: Inflation Expectation","Industrial Production: Total Index")
Units <- c("Index 2012=100, Seasonally Adjusted","Percent, Seasonally Adjusted","Percent, Not Seasonally Adjusted","Percent, Not Seasonally Adjusted","Index 2017=100, Seasonally Adjusted")

# Create dataframe for kable function
table_data <- data.frame(Variables, Description, Units)

# Table displaying variables, description, and units
kbl(table_data) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r visualize_vars}
# Use facet grid to visualize raw data for variables
fred_data %>% 
  ggplot(aes(x = Month, y = value)) + 
  geom_line() + 
  facet_grid(vars(symbol), scales = "free_y") + 
  labs(y = " ")
```

```{r transform}
# Transform variables
tdata <- fred_dataw %>% select(c(PCEPI, UNRATE, EXPINF1YR, MICH, INDPRO)) %>%
  mutate(infl = 1200*log(PCEPI/lag(PCEPI))) %>%                           # inflation
  mutate(dinfl = infl - lag(infl,1)) %>%                                  # differenced inflation
  mutate(dinfl12 = 100*log(PCEPI/lag(PCEPI,12)) - lag(infl,12)) %>%       # differenced inflation 12
  mutate(unrate = UNRATE - lag(UNRATE)) %>%                               # differenced unrate
  mutate(expinf1yr = EXPINF1YR - lag(EXPINF1YR)) %>%                      # differenced expected inf
  mutate(mich = MICH - lag(MICH)) %>%                                     # differenced mich
  mutate(indpro = 1200*log(INDPRO/lag(INDPRO))) %>%                       # differenced indpro
  # keep only transformed variables
  select(-c(PCEPI, UNRATE, EXPINF1YR, MICH, INDPRO)) %>%
  drop_na()

# Split the data into training and testing groups
train_data <- tdata %>% filter_index(~ "2018-12")
test_data <- tdata %>% filter_index("2019-01" ~ .)
```

```{r acf}
# Compare ACF plots before and after transformation
# fred_dataw %>% ACF(MICH) %>%
#   autoplot()
# tdata %>% ACF(mich) %>%
#   autoplot()
```


```{r melt}
# Observe the plots of the transformed variables
tdatam <- melt(tdata, "Month")
ggplot(tdatam, aes(Month, value)) + 
  geom_line() + 
  facet_wrap(~variable, scales = "free", ncol = 2)
```


<br>
<h5>Models</h5>
<br>

Using monthly data, the Phillips curve specification used is as follows:

<center>$\pi^{12}_{t}−\pi_{t−12}=\phi+\beta(B)\Delta\pi_{t−12}+\gamma(B)u_{t−12}+\varepsilon_t$</center>

```{r fit_models}
# Fit four models with the Phillips curve model specifications using unemployment rate, 1yr expected inflation, Michigan inflation expectations, and industrial production
fit_all <- train_data %>%
  model(
    mUN = TSLM(dinfl12 ~ 1 +
                 lag(dinfl,12) + lag(dinfl,13) + lag(dinfl,14) +
                 lag(dinfl,15) + lag(dinfl,16) + lag(dinfl,17) +
                 lag(dinfl,18) + lag(dinfl,19) + lag(dinfl,20) +
                 lag(dinfl,21) + lag(dinfl,22) + lag(dinfl,23) +
                 lag(unrate,12) + lag(unrate,13) + lag(unrate,14) +
                 lag(unrate,15) + lag(unrate,16) + lag(unrate,17) +
                 lag(unrate,18) + lag(unrate,19) + lag(unrate,20) +
                 lag(unrate,21) + lag(unrate,22) + lag(unrate,23)
                 ),
    mEXPINF = TSLM(dinfl12 ~ 1 +
                 lag(dinfl,12) + lag(dinfl,13) + lag(dinfl,14) +
                 lag(dinfl,15) + lag(dinfl,16) + lag(dinfl,17) +
                 lag(dinfl,18) + lag(dinfl,19) + lag(dinfl,20) +
                 lag(dinfl,21) + lag(dinfl,22) + lag(dinfl,23) +
                 lag(expinf1yr,12) + lag(expinf1yr,13) + lag(expinf1yr,14) +
                 lag(expinf1yr,15) + lag(expinf1yr,16) + lag(expinf1yr,17) +
                 lag(expinf1yr,18) + lag(expinf1yr,19) + lag(expinf1yr,20) +
                 lag(expinf1yr,21) + lag(expinf1yr,22) + lag(expinf1yr,23) 
                 ),
    mMICH = TSLM(dinfl12 ~ 1 +
                 lag(dinfl,12) + lag(dinfl,13) + lag(dinfl,14) +
                 lag(dinfl,15) + lag(dinfl,16) + lag(dinfl,17) +
                 lag(dinfl,18) + lag(dinfl,19) + lag(dinfl,20) +
                 lag(dinfl,21) + lag(dinfl,22) + lag(dinfl,23) +
                 lag(mich,12) + lag(mich,13) + lag(mich,14) +
                 lag(mich,15) + lag(mich,16) + lag(mich,17) +
                 lag(mich,18) + lag(mich,19) + lag(mich,20) +
                 lag(mich,21) + lag(mich,22) + lag(mich,23) 
                 ),
    mINDPRO = TSLM(dinfl12 ~ 1 +
                 lag(dinfl,12) + lag(dinfl,13) + lag(dinfl,14) +
                 lag(dinfl,15) + lag(dinfl,16) + lag(dinfl,17) +
                 lag(dinfl,18) + lag(dinfl,19) + lag(dinfl,20) +
                 lag(dinfl,21) + lag(dinfl,22) + lag(dinfl,23) +
                 lag(indpro,12) + lag(indpro,13) + lag(indpro,14) +
                 lag(indpro,15) + lag(indpro,16) + lag(indpro,17) +
                 lag(indpro,18) + lag(indpro,19) + lag(indpro,20) +
                 lag(indpro,21) + lag(indpro,22) + lag(indpro,23) 
                 )
    )

# Fit the combination model
fit_combo <- fit_all %>% mutate(combo = (mUN + mEXPINF + mMICH + mINDPRO)/4)
```

<br>
<h5>Estimation and Results</h5
<br>

```{r forecast}
# Forecast and plot the estimated models
forecast <- fit_combo %>% forecast(new_data = test_data) 
forecast %>% autoplot(filter(tdata, year(Month) > 2016), level = c(95))
```

```{r accuracy}
# Assess in-sample forecast accuracy
accuracy(fit_combo)
# Assess out-of-sample forecast accuracy
accuracy(forecast, tdata)
```

<br>
<h5>Conclusion</h5>
<br>
